=== 2.4.3 Limitations
== 2.5 Adversarial Motion Priors

Adversarial Motion Priors (AMP), introduced by @peng_amp_2021, address the
scalability limitations of reward-engineered imitation by replacing the
handcrafted multi-term objective with a learned discriminator that
automatically captures the statistical characteristics of the reference motion
data. The central insight is that natural motion can be defined not by
explicit per-joint kinematic metrics synchronized to a single clip, but by a
distribution: the set of state transitions that "look like" the reference
data. This approach draws on the adversarial training framework from
Generative Adversarial Networks goodfellow_gan_2014 and its application to
imitation learning in Generative Adversarial Imitation Learning
ho_ermon_2016.

=== 2.5.1 Architecture and Variable Definitions

The full AMP training loop is illustrated in fig_amp and involves the
following components, each of which is defined precisely below.

The *environment* advances the physics simulation by one timestep given an
action $a_t in RR^(n_"act")$, producing a new state $s_{t+1}$ and a
complete state transition $(s_t, s_{t+1})$. Here $n_"act"$ is the
dimensionality of the action space — the number of joint angle targets output
by the policy. For a 12-degree-of-freedom quadruped character, $n_"act" = 12$.

The *state* $s_t in RR^(n_s)$ is a proprioceptive description of the
character's current physical configuration, following the same convention as
DeepMimic: root position and orientation, linear and angular velocities, and
local joint angles and velocities, all expressed in the character's root
coordinate frame @peng_amp_2021. Unlike DeepMimic, AMP does not include a
phase variable $phi$ in $s_t$, because the discriminator does not require
temporal synchronization with a specific clip — it evaluates each transition
independently.

The *policy* $pi_theta(a_t | s_t, g_t)$ is the actor network, parameterized
by weights $theta$, that maps the current state and task goal to a Gaussian
distribution over actions, from which joint angle targets $a_t$ are sampled.
The policy receives two separate inputs at every timestep: the proprioceptive
state $s_t$, and the task goal $g_t$. As discussed in Section 2.4, these
serve distinct roles — $s_t$ describes the current physical configuration
of the character, while $g_t$ specifies the high-level behavioral objective
to be accomplished.

The *task goal* $g_t$ is a runtime-specified conditioning vector that
communicates the desired high-level behavior to the policy. In the locomotion
setting, $g_t = d^*_t in RR^2$ is a unit vector specifying a target heading
direction in the horizontal plane; during training it is randomized at each
episode, and at deployment it is controlled by the user via joystick or a
navigation module @peng_amp_2021. The arrow $g -> pi$ in fig_amp
represents this direct input: the policy network concatenates $g_t$ with
$s_t$ and processes both through its hidden layers to produce action $a_t$.

The *dataset* $cal(M)$ is an unstructured collection of motion capture clips
— in this thesis, the MANN dog dataset zhang_mann_2018. Unlike DeepMimic,
AMP imposes no requirements on clip ordering, clip boundaries, temporal
annotations, or skill labels. The dataset is accessed by randomly sampling
transition pairs $(s, s') ~ cal(M)$, where $s$ and $s'$ are consecutive
frames extracted from any clip.

The *motion prior* $D_psi(s_t, s_{t+1}) in [0, 1]$ is the discriminator
network, parameterized by weights $psi$, that receives a state transition
pair as input and is trained to distinguish transitions drawn from the
reference dataset $cal(M)$ from those generated by the policy during
simulation @peng_amp_2021. It is optimized using a least-squares objective
augmented by a gradient penalty gulrajani_2017 for training stability:

$ cal(L)_D = EE_((s,s') ~ cal(M))[(D_psi (s, s') - 1)^2]
           + EE_((s,s') ~ pi)  [(D_psi (s, s') + 1)^2]
           + lambda_"gp" dot EE[|| nabla_psi D_psi ||^2] $

where $cal(M)$ denotes sampling from the reference dataset, $pi$ denotes
sampling from the current policy's rollout, and $lambda_"gp"$ is the
gradient penalty coefficient — the most critical hyperparameter for
discriminator training stability @peng_amp_2021.

The *style reward* $r^S_t in [0, 1]$ is computed from the discriminator's
output and serves as the learned motion quality signal:

$ r^S_t (s_t, s_{t+1}) = max(0, 1 - 0.25 dot (D_psi (s_t, s_{t+1}) - 1)^2) $

This reward approaches 1 when the policy produces transitions that the
discriminator classifies as indistinguishable from the reference data, and
approaches 0 for transitions that fall outside the reference distribution
@peng_amp_2021. The arrow $r^S_t -> plus.o$ in fig_amp represents
this signal flowing into the reward aggregation node.

The *task reward* $r^G_t in RR$ evaluates the character's progress toward
the high-level goal $g_t$ and takes the same form as in DeepMimic:

$ r^G_t = exp[-2.5 max(0, v^* - v_t^top d^*_t)^2] $

where $v^*$ is the desired speed and $v_t$ is the character's center-of-mass
velocity @peng_amp_2021. The arrow $r^G_t -> plus.o$ in fig_amp
represents this signal entering the reward aggregation node alongside
$r^S_t$.

The *total reward* $r_t$ is the sum of both components, aggregated at the
$plus.o$ node and fed back to update the policy via PPO:

$ r_t = w^S dot r^S_t + w^G dot r^G_t $

where $w^S$ and $w^G$ are scalar weights balancing motion naturalness
against task fulfillment @peng_amp_2021. The arrow $r_t -> pi$ in
fig_amp represents this combined learning signal flowing back to update the
policy parameters $theta$ via PPO.

=== 2.5.2 Key Advantages Over DeepMimic

The AMP formulation eliminates all three limitations of DeepMimic identified
in Section 2.4. First, because the discriminator evaluates randomly sampled
transition pairs $(s_t, s_{t+1})$ independently of clip boundaries and
without a phase variable, a single policy can be trained on an entire
unstructured motion library simultaneously, without requiring separate
per-clip policies or a clip selection mechanism
@peng_amp_2021. Second, because the style reward is produced by a learned
function rather than a handcrafted formula, no manual reward weight
specification is required beyond the single scalar $w^S$. Third, because
the discriminator operates on state transitions rather than absolute poses,
the reference dataset does not need to be precisely retargeted to the
character's morphology at the joint level — the discriminator learns
what constitutes a natural transition directly from the data.

Crucially, both the task goal $g_t$ and the task reward $r^G_t$ remain
present in AMP and serve the same dual purpose as in DeepMimic: $g_t$
directly conditions the policy at runtime to specify *where* the character
should go, while $r^G_t$ provides the learning signal that teaches the
policy to pursue that goal effectively. The style reward $r^S_t$ from the
discriminator adds the complementary signal that teaches the policy *how*
to move, without prescribing specific joint configurations. This separation
of concerns — style from task — is the architectural core of AMP, and
produces policies that are simultaneously physically natural (governed by
$r^S_t$) and goal-directed (governed by $r^G_t$ and $g_t$).

#bibliography("zotero.bib", style: "apa")